# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: 'Pipeline automation for FE'
  imageRepository: 'bootcampquizapife'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: "Build"
  jobs:
  - job: BuildFrontendJob
    displayName: "Build Frontend"
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
        displayName: 'Install Node.js'

    - script: |
          npm install
          npm run build
      displayName: 'npm install and build'

- stage: BuildAndPush
  displayName: Build and publish stage
  jobs:
   - job: Build
     displayName: Build job
     pool:
       name: QuizPool
     steps:
      - task: Docker@2
        displayName: Build and publish image to ACR
        inputs:
          command: buildAndPush
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: $(imageRepository)
          dockerfile: $(dockerfilePath)
          tags: |
            latest
            $(tag)


